version: '4.1'
services:
  spring-boot-kotlin:
    image: project-2:latest
    container_name: project-2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    links:
      - cassandra
    restart: always
    stdin_open: true
    tty: true

  cassandra:
    image: cassandra:latest
    container_name: cassandra-project2
    ports:
      - "9042:9042"
    expose:
      - "9042"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 192.168.0.111